let saborEmpanada=prompt("digita el sabor de la empanada")
let saborGaseosa=prompt("digita el sabor de la gaseosa")
let nombrePostre=prompt("nombre de su postre")
let cantidadDeEmpanadas=Number(prompt("su cantidad de empanadas"))
let cantidadDegaseosas=Number(prompt("cantidad de gaseosas"))
let cantidadDepostres=Number(prompt("ponga su cantidad de postres"))
